# Copyright (c) 2019 All Rights Reserved WestBot

language: cpp
compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gcc-arm-none-eabi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - git submodule update --init --recursive
  - make
