# Copyright (c) 2019 All Rights Reserved WestBot

language: cpp
compiler: g++

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install gcc-arm-none-eabi

script:
  - cd travis
  - git submodule update --init --recursive
  - make -j7

after_success:
  - echo 'DONE'
